In [1]:
import pandas as pd

cardata = { "Mercedes": [2, 4, 0, 4, 0, 3], "Ford": [3, 0, 0, 1, 6, 12], "Tata":[9, 3, 4, 1, 0, 0], "Renault":[12, 1, 0, 0, 3, 1]}
carsales = pd.DataFrame(cardata)
carsales.index.rename("Sales place", inplace=True)
carsales.rename(index={0: "One", 1: "Two", 2: "Three", 3: "Four", 4: "Five", 5: "Six"}, inplace=True)

print(carsales)

             Mercedes  Ford  Tata  Renault
Sales place                               
One                 2     3     9       12
Two                 4     0     3        1
Three               0     0     4        0
Four                4     1     1        0
Five                0     6     0        3
Six                 3    12     0        1


# The `info()` function

## Get *DataFrame* info

In [2]:
print(carsales.info())

<class 'pandas.core.frame.DataFrame'>
Index: 6 entries, One to Six
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Mercedes  6 non-null      int64
 1   Ford      6 non-null      int64
 2   Tata      6 non-null      int64
 3   Renault   6 non-null      int64
dtypes: int64(4)
memory usage: 240.0+ bytes
None


## Get *Series* object info

In [3]:
print(carsales["Tata"].info())

<class 'pandas.core.series.Series'>
Index: 6 entries, One to Six
Series name: Tata
Non-Null Count  Dtype
--------------  -----
6 non-null      int64
dtypes: int64(1)
memory usage: 96.0+ bytes
None


We can get a *DataFrame* info out of the required *Series* from an existing DataFrame.

In [4]:
print(carsales[["Tata", "Ford"]].info())

<class 'pandas.core.frame.DataFrame'>
Index: 6 entries, One to Six
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Tata    6 non-null      int64
 1   Ford    6 non-null      int64
dtypes: int64(2)
memory usage: 144.0+ bytes
None


# The `type()` function

In [8]:
print(carsales.loc["Two", "Ford"])
print(type(carsales.loc["Two", "Ford"]))

0
<class 'numpy.int64'>


Pandas converts all python *int* to numpy *int64*, because they are faster for calculations, amongst others

In [9]:
print(carsales.iloc[2, 2])
print(type(carsales.iloc[2, 2]))

4
<class 'numpy.int64'>


## The `DataFrame.dtypes` property

In [10]:
print(carsales.dtypes)

Mercedes    int64
Ford        int64
Tata        int64
Renault     int64
dtype: object


## Cast *int64* to Python's *int*

In [11]:
y = carsales.loc["Two", "Ford"]
print(type(y))

<class 'numpy.int64'>


In [12]:
print(type(int(y)))

<class 'int'>


## Methods to get the data back to Python variables/objects

### Numpy's `tolist()`

In [17]:
import numpy as np
a = np.uint32([1, 2])
a_list = list(a)
a_list
print(type(a_list[0]))

<class 'numpy.uint32'>


In [16]:
a_tolist = a.tolist()
a_tolist
print(type(a_tolist[0]))

<class 'int'>


In [18]:
z = carsales.loc["Two", "Ford"]
print(z)
print(z.tolist())
print(type(z.tolist()))

0
0
<class 'int'>


### Pandas' `Series.to_list()`

In [22]:
list = carsales.Ford.to_list()
print(list)
for i in list:
    print(type(i))

[3, 0, 0, 1, 6, 12]
<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>


### Numpy's `ndarray.item()`

In [32]:
import numpy as np
np.random.seed(123)
x = np.random.randint(9, size=(3, 3))
print(x)
print(x.item(3))
print(type(x.item(3)))
print(x.item(7))
print(type(x.item(7)))
print(x.item((0, 1)))
print(type(x.item((0, 1))))
print(x.item((2, 2)))
print(type(x.item((2, 2))))

[[2 2 6]
 [1 3 6]
 [1 0 1]]
1
<class 'int'>
0
<class 'int'>
2
<class 'int'>
1
<class 'int'>
